#!/usr/bin/env python3
from os.path import islink, exists, dirname, join, realpath
from os import symlink
from shutil import move
from pathlib import Path


DOWNLOADS = [
    "https://github.com/latex-lsp/texlab/releases/download/v3.3.1/texlab-x86_64-linux.tar.gz"
]

LINKS = {
    "spacemacs":"~/.spacemacs",
    "Xdefaults":"~/.Xdefaults",
    "zshrc":"~/.zshrc",
    "i3config":"~/.config/i3/config",
    "i3statusconfig":"~/.config/i3status/config",
    "latexmkrc":"~/.latexmkrc",
    "urxvt_ext":"~/.urxvt/ext",
    "screenlayout":"~/.screenlayout",
    "zshrc.d":"~/.zshrc.d",
    "arduino/mbed_nano.platform.txt":"~/.arduino15/packages/arduino/hardware/mbed_nano/2.5.2/platform.local.txt",
    "arduino/avr.platform.txt":"~/.arduino15/packages/arduino/hardware/avr/1.8.3/platform.local.txt",
}

dotfiles_path = dirname(realpath(__file__))

for src, trg in LINKS.items():
    src = join(dotfiles_path, src)
    trg = Path(trg).expanduser()
    if exists(trg) and not islink(trg):
        move(trg, f"{trg}.bak")
        print("target already exists and is not a symlink, creating backup")
    Path(dirname(trg)).mkdir(parents=True, exist_ok=True)
    if islink(trg):
        print(f"{trg} already linked")
    else:
        print(f"{src} -> {trg}")
        symlink(src, trg)
