#!/usr/bin/env python3
from os.path import islink, exists, dirname, join, realpath
from os import symlink
from shutil import move
from pathlib import Path


src_files = [
    "spacemacs",
    "Xdefaults",
    "zshrc",
    "i3config",
    "i3statusconfig",
    "urxvt_ext",
    "screenlayout",
    "zshrc.d",

]
target_files = [
    "~/.spacemacs",
    "~/.Xdefaults",
    "~/.zshrc",
    "~/.config/i3/config",
    "~/.config/i3status/config",
    "~/.urxvt/ext",
    "~/.screenlayout",
    "~/.zshrc.d"
]

src_folders = [
    "bin",
]

trg_folders = [
    "~/bin",
]

dotfiles_path = dirname(realpath(__file__))

print("dotfiles location:", dotfiles_path)
src_files = [join(dotfiles_path, f) for f in src_files]
target_files = [Path(f).expanduser() for f in target_files]

for src, trg in zip(src_files, target_files):
    print(f"{src} -> {trg}")
    if exists(trg) and not islink(trg):
        move(trg, f"{trg}.bak")
        print("target already exists and is not a symlink, creating backup")
    Path(dirname(trg)).mkdir(parents=True, exist_ok=True)
    if islink(trg):
        print(f"{trg} already linked")
    else:
        symlink(src, trg)
